#!/bin/bash

PIDFILE=/home/%(name)s/app.pid

case $1 in
   start)
      echo $$ > ${PIDFILE};
      source /home/%(name)s/venv/bin/activate
      PORT=%(port)d exec python /home/%(name)s/app/server.py 2>/dev/null
      ;;
    stop)
      kill `cat ${PIDFILE}` ;;
    *)
      echo "usage: %(name)s {start|stop}" ;;
esac
exit 0