#!/bin/bash

PIDFILE=/home/{name}/app.pid

case $1 in
   start)
      echo $$ > ${PIDFILE};
      source /home/{name}/venv/bin/activate
      PORT={port} exec python /home/{name}/app/server.py 2>/dev/null
      ;;
    stop)
      kill `cat ${PIDFILE}` ;;
    *)
      echo "usage: {name} {start|stop}" ;;
esac
exit 0